name         'rfletcher-bats'
version      '0.0.1'
license      'MIT License'
summary      'A Puppet module for Bats, a Bash script test framework'
description  'Install or remove Bats'
project_page 'https://github.com/rfletcher/puppet-bats'
dependency   'puppetlabs/vcsrepo', '>= 1.2.0'
